create_table: |
  CREATE TABLE IF NOT EXISTS {table_name} (
    date DATE PRIMARY KEY,
    {columns}
  );
insert_data: |
  INSERT INTO {table_name} ({columns}) VALUES ({values})
  ON CONFLICT (date) DO UPDATE SET {update_columns};
get_existing_tables: |
  SELECT table_name
  FROM information_schema.tables
  WHERE table_schema = 'public';
get_latest_date: |
  SELECT MAX(date) FROM {table_name};
